[tools]
claude = "latest"
codex = "latest"
conan = "latest"
gh = "latest"
go = "latest"
node = "latest"
"npm:@xai-official/grok" = "latest"
python = "latest"
ruby = "latest"
zig = "latest"
zls = "latest"

[settings]
idiomatic_version_file_enable_tools = ["ruby"]

[settings.ruby]
compile = false
