CompileFlags:
  Add: [
    "-I/usr/include/c++/9",
    "-I/usr/include/c++/10",
    "-I/usr/include/c++/11",
    "-I/usr/include/c++/12",
    "-I/usr/include/x86_64-linux-gnu/c++/9",
    "-I/usr/include/x86_64-linux-gnu/c++/10",
    "-I/usr/include/x86_64-linux-gnu/c++/11",
    "-I/usr/include/x86_64-linux-gnu/c++/12",
    "-I/usr/lib/llvm-14/lib/clang/14/lib",
    "-I/usr/lib/llvm-11/lib/clang/11.0.0/include",
    "-I/usr/lib/llvm-14/lib/clang/14.0.0/include",
    "-I/usr/include"
  ]
