-- @todo: enhance plugin configs.
-- refer:  https://github.com/tzachar/highlight-undo.nvim
return {
  "tzachar/highlight-undo.nvim",
  event = "VeryLazy", -- Load the plugin lazily
}
-- Explanation of Key Configuration Options
--
--     Plugin Declaration:
--         The return statement is used to declare the plugin. The first element is the plugin name ("tzachar/highlight-undo.nvim").
--         The event = "VeryLazy" ensures that the plugin is loaded lazily, which improves startup time.
--
--     Configuration Function:
--         The config function is used to set up the plugin. Inside this function, we call require("highlight-undo").setup() with the configuration options.
--
--     Highlight Group:
--         The hlgroup option allows you to specify the highlight group used for the undo/redo changes. You can customize this to match your color scheme.
--
--     Duration:
--         The duration option specifies how long (in milliseconds) the highlight should remain visible after an undo or redo operation. The default is 300 ms.
--
--     Keymaps:
--         The keymaps section allows you to customize the keybindings for undo and redo operations. By default, u is used for undo and <C-r> for redo.
--         You can also enable visual undo and redo by setting undo_visual and redo_visual to true.
--
--     Custom Highlight Colors:
--         The highlight section allows you to customize the colors used for the highlight. You can set the foreground (guifg), background (guibg), and text style (gui).
--
-- Example of Custom Highlight Colors
--
-- If you want to customize the highlight colors, you can modify the highlight section like this:
--
-- highlight = {
--   guifg = "#FF0000", -- Red text color
--   guibg = "#0000FF", -- Blue background color
--   gui = "bold", -- Bold text
-- },
--
-- This will make the undo/redo changes appear with red text on a blue background, and the text will be bold.
-- How to Use
--
--     Save this configuration in your LazyVim plugin directory, typically under ~/.config/nvim/lua/plugins/highlight-undo.lua.
--     Ensure that the plugin is loaded by LazyVim by adding it to your plugin list if necessary.
--
-- Additional Features
--
--     Visual Undo/Redo: You can enable visual undo and redo by setting undo_visual and redo_visual to true. This will show a visual indicator of the changes made by undo and redo operations.
--     Custom Keymaps: You can change the default keybindings for undo and redo by modifying the keymaps section.
--
-- Conclusion
--
-- This configuration integrates the highlight-undo.nvim plugin into LazyVim, allowing you to see the changes made by undo and redo operations with customizable highlights. You can further customize the colors, duration, and keybindings to suit your preferences.
